/** Semua rute statis situs (dipakai sitemap dan uji e2e). */
export const RUTE_STATIS = [
  "/",
  "/profil",
  "/profil/sejarah",
  "/profil/visi-misi",
  "/profil/struktur-organisasi",
  "/profil/akreditasi",
  "/profil/guru-staf",
  "/akademik",
  "/akademik/kurikulum",
  "/akademik/mata-pelajaran",
  "/akademik/program-unggulan",
  "/akademik/ekstrakurikuler",
  "/informasi",
  "/informasi/berita",
  "/informasi/pengumuman",
  "/informasi/agenda",
  "/informasi/prestasi",
  "/informasi/unduhan",
  "/galeri",
  "/ppdb",
  "/kontak",
] as const;
